# Default values for alliance-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


### DEPLOY SECRETS WITH private helm chart 'secrets' from platform/secrets
## Name: imagePullSecret
## Description: Secret to pull images from our private repository.
imagePullSecret: regcred
## to create a regcred
## kubectl create secret docker-registry regcred --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword>

# REQUIREMENT: set a storage class with ability to serve ReadWriteMany
# Name: storageClassName
# Description: Set a storage class for the resources that are reused for multi-mount-points in cluster. To reduce wasteful copying we allow to use the same dataset volume to be mounted multiple times.
# Default: hostpath (works with docker-for-desktop)
storageClassName: hostpath

studio:
  image: #tell which image to deploy for studio
    repository: registry.demo.scaleout.se/studio:latest # point to the latest beta image
    pullPolicy: Always # used to ensure that each time we redeploy always pull the latest image

# Enable ingress if you want your to access the studio solution from a kubernetes host/localhost.
ingress:
  enabled: true
  image: #tell which image to deploy for studio
    repository: registry.demo.scaleout.se/ingress:latest
    pullPolicy: Always
  annotations:
  hosts:
    - host: platform.local

  # setup TLS if you have a platform certificate or use 'tls-acme' if you have certbot deployed and want to generate a certificate.
    #tls:
    #- secretName: platform-tls-secret
    #  hosts:
    #    - platform.local


service:
  type: ClusterIP #override if you want to use NodePort instead to access cluster services

#override if you want to try out a HA (HIGH AVAILABILITY) setup.
replicaCount: 1

# override if certain resource requirements should apply
resources: {}

# override if certain nodes should be used for the deployed resources.
nodeSelector: {}

# override if declaring that some criteria is tolerated for resource co-existing.
tolerations: []

affinity: {}



# Postgres default credentials for backend DB. Override for security!
postgres:
  db:
    name: postgres
    user: postgres
    password: postgres


# default credentials for rabbitmq. override in production!
rabbit:
  username: admin
  password: LJqEG9RE4Fd+ZbVWoJzZ+/IOQEI=
