apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-file-controller
  name: {{ .Release.Name }}-file-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Release.Name }}-file-controller
    spec:
      containers:
      - env:
        - name: PROJECT_DIR
          value: /app/work
        image: scaleoutsystems/file-controller:master
        name: {{ .Release.Name }}-file-controller
        ports:
        - containerPort: 5000
        resources: {}
        volumeMounts:
        - mountPath: /app/work
          name: project-files
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end }}
      volumes:
      - name: project-files
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-project-files
status: {}
