apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-labs-ingress
  annotations:
    kubernetes.io/tls-acme: 'true'
    #nginx.ingress.kubernetes.io/auth-url: "/auth/"
    #ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
    #nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - labs.{{ .Release.Name }}.{{ .Values.global.domain }}
    secretName: {{ .Release.Name }}-labs-tls-secret
  rules:
  - host: labs.{{ .Release.Name }}.{{ .Values.global.domain }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-labs-service
            servicePort: 8888
