apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-project-ae-secret
type: Opaque
data:
  accesskey: {{ .Values.minio.access_key | b64enc | quote }}
  secretkey: {{ .Values.minio.secret_key | b64enc | quote }}