apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-minio-data
  name: {{ .Release.Name }}-minio-data
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.storageClassName | default "hostpath" }}
  resources:
    requests:
      storage: {{ .Values.minio.volume.size }}
status: {}
