apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    #kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: 'true'
  name: {{ .Release.Name }}-minio-ingress
spec:
  rules:
    - host: minio.{{ .Release.Name }}.{{ .Values.global.domain }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-minio
            servicePort: 9000
  tls:
    # This secret must exist beforehand
    # The cert must also contain the subj-name fortune-teller.stack.build
    # https://github.com/kubernetes/ingress-nginx/blob/master/docs/examples/PREREQUISITES.md#tls-certificates
    - secretName: {{ .Release.Name }}-minio-tls-secret
      hosts:
        - {{ .Release.Name }}.minio.{{ .Values.global.domain }}
