apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-{{ .Values.deployment.version }}
  labels:
    run: {{ .Values.deployment.name }}-{{ .Values.deployment.version }}
spec:
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
  selector:
    app: {{ .Values.deployment.name }}-{{ .Values.deployment.version }}