apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    # nginx.ingress.kubernetes.io/auth-url: https://{{ .Values.global.domain }}/api/deploymentInstances/auth/
    # nginx.ingress.kubernetes.io/auth-method: POST
    # nginx.ingress.kubernetes.io/auth-response-headers: UserID
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: {{ .Values.deployment.name }}-{{ .Values.deployment.version }}-ingress
  namespace: {{ .Values.namespace }}
  labels:
    io.kompose.service: {{ .Values.deployment.name }}-{{ .Values.deployment.version }}-ingress
spec:
  rules:
    - host: {{ .Values.deployment.endpoint }}
      http:
        paths:
        - path: {{ .Values.deployment.path }}(.*)
          backend:
            serviceName: {{ .Values.appname }}
            servicePort: 80
  tls:
    - secretName: prod-ingress
      hosts:
        - {{ .Values.deployment.endpoint }}