apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-url: https://{{ .Values.global.domain }}/api/deploymentInstances/auth/
    nginx.ingress.kubernetes.io/auth-method: POST
    nginx.ingress.kubernetes.io/auth-response-headers: UserID
    #kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/ssl-redirect: "true"
    #kubernetes.io/tls-acme: 'true'
    # nginx.ingress.kubernetes.io/proxy-body-size: "5500m"
  name: {{ .Values.deployment.name }}-{{ .Values.deployment.version }}-ingress
  labels:
    io.kompose.service: {{ .Values.deployment.name }}-{{ .Values.deployment.version }}-ingress
spec:
  rules:
    - host: {{ .Values.deployment.endpoint }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ .Values.deployment.name }}-{{ .Values.deployment.version }}
            servicePort: 80
  tls:
    - secretName: prod-ingress
      hosts:
        - {{ .Values.deployment.name }}-{{ .Values.deployment.version }}.{{ .Values.global.domain }}