# Default values for alliance-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

controller:
  image:
    repository: registry.demo.scaleout.se/chart-controller
    pullPolicy: Always
  branch: master 

imagePullSecrets:
  - name: regcred


cluster_config: |-
    apiVersion: v1
    kind: Config
    clusters:
    - name: "local"
      cluster:
        server: "your.server.here"
    users:
    - name: "local"
      user:
        token: "your.token.here"

    contexts:
    - name: "local"
      context:
        user: "local"
        cluster: "local"

    current-context: "local"
