



labs:
  image: jupyter/minimal-notebook:latest
  repository: "https://github.com/scaleoutsystems/aml-example-project.git"
  secret: ""

global:
  domain: platform.local

minio:
  access_key: minio
  secret_key: minio123

defaultBucket:
  enabled: True
  policy: download

service:
  type: ClusterIP

imagePullSecret: regcred
#storageClassName: aws-efs
