# Default values for alliance-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1


global:
  domain: alliance.scaleout.se

alliance:
  user: morgan
  project: test
  apiUrl: "http://studio:8080"

minio:
  access_key: minio
  secret_key: minio123

controller:
  image:
    repository: scaleoutsystems/controller
    tag: latest
    pullPolicy: Always

monitor:
  image:
    repository: scaleoutsystems/monitor
    tag: latest
    pullPolicy: Always

orchestrator:
  repository: "git@github.com:scaleoutsystems/scaleout-alliance-orchestrator-sdk.git"
  image:
    repository: scaleoutsystems/orchestrator
    tag: latest
    pullPolicy: Always


#imagePullSecrets:
#  - name: regcred

nameOverride: ""
fullnameOverride: ""


service:
  type: NodePort
  controller: 30398
  minio: 30397

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
