
project:
  name: test
labs:
  image: pharmbio/pharmbio-notebook:tf-2.1.0-gpu
  #image: jupyter/minimal-notebook:latest

  gpu:
    enabled: false

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: acceleration
            operator: In
            values:
            - gpu

global:
  domain: platform.local

# Enable this if you intend to pull an image from a protected repository.
#imagePullSecrets:
#  - name: regcred

minio:
  access_key: minio
  secret_key: minio123
  bucket: dataset
