
project:
  name: test
labs:
  image: jupyter/minimal-notebook:latest
  repository: "git@github.com:scaleoutsystems/digits-example-project.git"
  requests:
    memory: 256m
    cpu: 200m
#  limits:
#    memory: 1Gi
#    cpu: 500m

global:
  domain: platform.local

imagePullSecrets:
  - name: regcred
