apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-ingress
  name: {{ .Release.Name }}-ingress
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  selector:
    io.kompose.service: {{ .Release.Name }}-ingress
status:
  loadBalancer: {}
