{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
  {{- with .Values.ingress.annotations }}
     {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    io.kompose.service: {{ .Release.Name }}-ingress
spec:
  {{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        - path: /
          backend:
            serviceName: {{ $.Release.Name }}-studio
            servicePort: 8080
        - path: /static/
          backend:
            serviceName: {{ $.Release.Name }}-studio
            servicePort: 8080
  {{- end }}
{{- end }}
