apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-studio-db-pvc
  name: {{ .Release.Name }}-studio-db-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: {{ .Values.storageClassName | default "hostpath" }}
  resources:
    requests:
      storage: 5Gi
status: {}
