apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-controller
  name: {{ .Release.Name }}-controller
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Release.Name }}-controller
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        image: "{{ .Values.controller.image.repository }}:{{ .Chart.AppVersion }}"
        name: {{ .Release.Name }}-controller
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - name: config
          mountPath: "/root/.kube/"
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: config
        secret:
          secretName: {{ .Release.Name }}-clusterconfig-secret


status: {}
