apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-celery-worker
  name: {{ .Release.Name }}-celery-worker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Release.Name }}-celery-worker
    spec:
      containers:
      - args:
        - sh
        - ./scripts/run_worker.sh
        env:
        - name: GET_HOSTS_FROM
          value: dns
        image: {{ .Values.studio.image.repository }}
        imagePullPolicy: Always
        name: {{ .Release.Name }}-celery-worker
        resources: {}
        volumeMounts:
        - mountPath: /app/celery
          name: celery-worker-claim0
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end }}
      restartPolicy: Always
      volumes:
      - name: celery-worker-claim0
        persistentVolumeClaim:
          claimName: celery-worker-claim0
status: {}
