apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: data-repositories
  name: data-repositories
spec:
  storageClassName: {{ .Values.repositories.storageClassName }}
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
