apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-ingress
  name: {{ .Release.Name }}-ingress
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Release.Name }}-ingress
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        image: registry.demo.scaleout.se/ingress:latest
        name: {{ .Release.Name }}-ingress
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          name: nginx-conf
          readOnly: true
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end }}
      restartPolicy: Always
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-config-configmap
          items:
          - key: nginx.conf
            path: nginx.conf
