apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: studio
  name: studio
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: studio
    spec:
      containers:
      - args:
        - sh
        - scripts/run_web.sh
        env:
        - name: GET_HOSTS_FROM
          value: dns
        image: registry.demo.scaleout.se/studio:latest
        imagePullPolicy: Always
        name: studio
        resources: {}
        volumeMounts:
        - mountPath: /app/repos
          name: data-repositories
      imagePullSecrets:
        - name: basic-auth-key
      restartPolicy: Always
      volumes:
      - name: data-repositories
        persistentVolumeClaim:
          claimName: data-repositories
