apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-studio
  name: {{ .Release.Name }}-studio
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Release.Name }}-studio
    spec:
      containers:
      - args:
        - sh
        - scripts/run_web.sh
        env:
        - name: GET_HOSTS_FROM
          value: dns
        image: {{ .Values.studio.image.repository }}
        imagePullPolicy: Always
        name: {{ .Release.Name }}-studio
        resources: {}
        volumeMounts:
        - mountPath: /app/repos
          name: data-repositories
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end }}
      restartPolicy: Always
      volumes:
      - name: data-repositories
        persistentVolumeClaim:
          claimName: data-repositories
