apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: {{ .Release.Name }}-orchestrator
  name: {{ .Release.Name }}-orchestrator
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: {{ .Release.Name }}-orchestrator
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - args:
        - sh
        - ./runweb.sh
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: MINIO_HOST
          value: {{ .Release.Name }}-minio
        - name: CONTROLLER_HOST
          value: {{ .Release.Name }}-controller
        image: "{{ .Values.orchestrator.image.repository }}:{{ .Values.orchestrator.image.tag }}"
        name: {{ .Release.Name }}-orchestrator
        resources: {}
      #  volumeMounts:
      #  - mountPath: /app/
      #    name: orchestrator-claim0
      #  - mountPath: /app/data
      #    name: orchestrator-claim1
      restartPolicy: Always
      #volumes:
      #- name: orchestrator-claim0
      #  persistentVolumeClaim:
      #    claimName: orchestrator-claim0
      #- name: orchestrator-claim1
      #  persistentVolumeClaim:
      #    claimName: orchestrator-claim1
status: {}
