
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-orchestrator-configmap
data:
  # Configuration values can be set as key-value properties
  project.yaml: |-
    Config:
      hosts:
        minio_host: {{ .Release.Name }}-minio
        minio_port: 9000
        # {{ .Values.service.minio }}
        controller_host: {{ .Release.Name}}-controller
        controller_port: 12080
        #{{ .Values.service.controller }}
    Project:
      entry_points:
        predict:
          command: python3 predict.py
        train:
          command: python3 train.py
        validate:
          command: python3 validate.py
      access_key: orchestrator
