apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: prod-ingress
spec:
  secretName: prod-ingress
  dnsNames:
  - "*.127.0.0.1.nip.io"
  - "*.studio.127.0.0.1.nip.io"
  issuerRef:
    name: selfsigned-issuer