apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-labs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-labs-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-labs-app
    spec:
    {{ if .Values.labs.gpu }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: acceleration
                operator: In
                values:
                - gpu
    {{ end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        runAsUser: 65533  # to allow read of ssh key
      containers:
      - name: {{ .Release.Name }}-labs-app
        image: {{ .Values.labs.image }}
        ports:
        - containerPort: 8888
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        - name: NOTEBOOK_PASSWD_SHA1
          value: ""
        - name: NOTEBOOK_TOKEN
          value: ""
        #command: ["start-notebook.sh"]
        #args: ["--NotebookApp.token=''"]
        resources:
            {{ if .Values.labs.requests }}
            requests:
                {{ if .Values.labs.requests.memory }}
                memory: "{{ .Values.labs.requests.memory }}"
                {{ end }}
                {{ if .Values.labs.requests.cpu }}
                cpu: "{{ .Values.labs.requests.cpu }}"
                {{ end }}
            {{ end }}
            {{ if .Values.labs.limits}}
            limits:
                {{ if .Values.labs.limits.memory }}
                memory: "{{ .Values.labs.limits.memory }}"
                {{ end }}
                {{ if .Values.labs.limits.cpu }}
                cpu: "{{ .Values.labs.limits.cpu }}"
                {{ end }}
                {{ if .Values.labs.limits.gpu }}
                nvidia.com/gpu: "{{ .Values.labs.limits.gpu }}"
                {{ end }}
            {{ end }}
        volumeMounts:
        - name: homedir
          mountPath: /home/jovyan/
        - name: jupyterconf
          mountPath: /etc/jupyter/jupyter_notebook_config.py
          subPath: jupyter_notebook_config.py
        securityContext:
          allowPrivilegeEscalation: true
      volumes:
      - name: homedir
        persistentVolumeClaim:
          claimName: {{ .Values.project.name }}-project-files
      - name: jupyterconf
        configMap:
          name: {{ .Release.Name }}-jupyter-configmap
