apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-labs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-labs-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-labs-app
    spec:
    {{ if .Values.labs.gpu }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: acceleration
                operator: In
                values:
                - gpu
    {{ end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        runAsUser: 65533  # to allow read of ssh key
      {{ if .Values.labs.repository }}
      initContainers:
      - name: git-sync
        image: k8s.gcr.io/git-sync:v3.1.1
        env:
        - name: GIT_SYNC_REPO
          value: {{ .Values.labs.repository | quote }}
        - name: GIT_SYNC_BRANCH
          value: master
        - name: GIT_SYNC_DEST
          value: work
        - name: GIT_SSH_KEY_FILE
          value: /etc/git-secret/ssh
        - name: GIT_SYNC_SSH
          value: "true"
        - name: GIT_KNOWN_HOSTS
          value: "false"
        - name: GIT_SYNC_ONE_TIME
          value: "true"
        volumeMounts:
        - name: git
          mountPath: /tmp/git
        - name: git-secret
          mountPath: /etc/git-secret/
      {{ end }}
      containers:
      - name: {{ .Release.Name }}-labs-app
        image: {{ .Values.labs.image }}
        ports:
        - containerPort: 8888
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        command: ["start-notebook.sh"]
        args: ["--NotebookApp.token=''"]
        resources:
            {{ if .Values.labs.requests }}
            requests:
                memory: "{{ .Values.labs.requests.memory }}"
                cpu: "{{ .Values.labs.requests.cpu }}"
            {{ end }}
            {{ if .Values.labs.limits}}
            limits:
                memory: "{{ .Values.labs.limits.memory }}"
                cpu: "{{ .Values.labs.limits.cpu }}"
            {{ end }}
        volumeMounts:
        - name: git
          mountPath: /home/jovyan/
        - name: jupyterconf
          mountPath: /etc/jupyter/jupyter_notebook_config.py
          subPath: jupyter_notebook_config.py
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
      - name: git
        persistentVolumeClaim:
          claimName: {{ .Values.project.name }}-project-files
      {{ if .Values.labs.repository }}
      - name: git-secret
        secret:
          secretName: digits-example-ssh-secret
      {{ end }}
      - name: jupyterconf
        configMap:
          name: {{ .Release.Name }}-jupyter-configmap
