apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-labs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-labs-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-labs-app
    spec:
    {{ if .Values.labs.gpu }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: acceleration
                operator: In
                values:
                - gpu
    {{ end }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        runAsUser: 65533  # to allow read of ssh key
      containers:
      - name: {{ .Release.Name }}-labs-app
        image: {{ .Values.labs.image }}
        ports:
        - containerPort: 8888
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        - name: NOTEBOOK_PASSWD_SHA1
          value: ""
        - name: NOTEBOOK_TOKEN
          value: ""

        resources:
            {{ if .Values.labs.requests }}
            requests:
                {{ if .Values.labs.requests.memory }}
                memory: "{{ .Values.labs.requests.memory }}"
                {{ end }}
                {{ if .Values.labs.requests.cpu }}
                cpu: "{{ .Values.labs.requests.cpu }}"
                {{ end }}
            {{ end }}
            {{ if .Values.labs.limits}}
            limits:
                {{ if .Values.labs.limits.memory }}
                memory: "{{ .Values.labs.limits.memory }}"
                {{ end }}
                {{ if .Values.labs.limits.cpu }}
                cpu: "{{ .Values.labs.limits.cpu }}"
                {{ end }}
                {{ if .Values.labs.limits.gpu }}
                nvidia.com/gpu: "{{ .Values.labs.limits.gpu }}"
                {{ end }}
            {{ end }}
        volumeMounts:
        - name: homedir
          mountPath: /home/jovyan/
        - name: jupyterconf
          mountPath: /etc/jupyter/jupyter_notebook_config.py
          subPath: jupyter_notebook_config.py
        securityContext:
          allowPrivilegeEscalation: true
      - name: {{ .Release.Name }}-s3-sync
        image: registry.demo.scaleout.se/dataset-syncer:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        lifecycle:
          postStart:
            exec:
              command: ["mkdir","/home/jovyan/dataset"]
        env:
        - name: DUMB_INIT_VER
          value: 1.2.0
        - name: S3_BUCKET
          value: {{ .Values.minio.bucket | default "dataset" }}
        #- name: S3_REGION
        #  value: ap-southeast-2
        - name: MNT_POINT
          value: /home/jovyan/dataset
        - name: AWS_URL
          value: http://test-minio:9000
        - name: AWS_KEY
          value: {{ .Values.minio.access_key }}
        - name: AWS_SECRET_KEY
          value: {{ .Values.minio.secret_key }}
        volumeMounts:
        - name: homedir
          mountPath: /home/jovyan/
        - name: devfuse
          mountPath: /dev/fuse
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: homedir
        persistentVolumeClaim:
          claimName: {{ .Values.project.name }}-project-files
      - name: devfuse
        hostPath:
          path: /dev/fuse

      - name: jupyterconf
        configMap:
          name: {{ .Release.Name }}-jupyter-configmap
